// commands/news.js
const { Sparky, isPublic } = require("../lib");
const axios = require("axios");
const config = require("../config");

Sparky({
    name: "news",
    alias: ["පුවත්", "breaking", "n"],
    category: "news",
    fromMe: isPublic,
    desc: "ලෝකයේ අලුත්ම පුවත් ලබා ගැනීම"
}, async ({ client, m, args }) => {
    try {
        const botName = config.BOT_INFO?.split(";")[0] || "X-KADIYA-MD";

        await client.sendMessage(m.jid, { text: "📥 NewsAPI වෙතින් අලුත්ම පුවත් ලබාගනිමින් පවතී..." }, { quoted: m });

        // NewsAPI Global Headllines (කිසිදු country හෝ q සීමාවක් නොමැත)
        const apiKey = "15d4000cd98b4ec59387a8bbb1bb5372";
        const response = await axios.get(`https://newsapi.org/v2/top-headlines?language=en&apiKey=${apiKey}`, {
            timeout: 10000
        });

        const articles = response.data?.articles;

        if (!articles || articles.length === 0) {
            return await m.reply("❌ පුවත් සෙවීමේදී දෝෂයක් ඇතිවිය.");
        }

        const topNews = articles.slice(0, 5);
        
        let menuStatus = `
╭───────────────◉
│ *📰 ${botName} NEWS HUB*
├───────────────◉
│✨ Global News Service
├───────────────◉\n`;

        topNews.forEach((item, index) => {
            menuStatus += `│ *${index + 1}️⃣ ${item.title.substring(0, 50)}...*\n`;
        });

        menuStatus += `
╰────────────────◉
> ${botName} WhatsApp Bot

*Reply with (1 - 5):*
සම්පූර්ණ පුවත කියවීමට අංකයක් Reply කරන්න. 🧧
`;

        await client.sendMessage(m.jid, {
            image: { url: topNews[0].urlToImage || "https://res.cloudinary.com/dqlh378fb/image/upload/v1780800370/zanta_media_uploads/y2qrw8srsw1v4dsu5wxv.jpg" },
            caption: menuStatus
        }, { quoted: m });

        // ඕනෑම ආකාරයක Reply Text එකක් නිවැරදිව වෙන් කර හඳුනාගන්නා ශ්‍රිතය (Fix)
        const getMessageText = (msg) => {
            if (!msg?.message) return "";
            return (
                msg.message.conversation ||
                msg.message.extendedTextMessage?.text ||
                msg.message.templateButtonReplyMessage?.selectedId ||
                msg.message.buttonsResponseMessage?.selectedButtonId ||
                ""
            ).trim();
        };

        // Reply Filter එක
        const filter = (msg) => {
            if (!msg?.message) return false;
            if (msg.key.remoteJid !== m.jid) return false;
            if (msg.key.fromMe) return false;

            const text = getMessageText(msg);
            return ["1", "2", "3", "4", "5"].includes(text);
        };

        // තත්පර 60ක් පරිශීලකයාගේ පිළිතුර සඳහා රැක සිටීම
        const replyMsg = await new Promise((resolve) => {
            const handler = (chatUpdate) => {
                const msg = chatUpdate.messages?.[0];
                if (filter(msg)) {
                    client.ev.off("messages.upsert", handler);
                    resolve(msg);
                }
            };

            client.ev.on("messages.upsert", handler);

            setTimeout(() => {
                client.ev.off("messages.upsert", handler);
                resolve(null);
            }, 60000); 
        });

        if (!replyMsg) return;

        // තෝරාගත් අංකය නිවැරදිව ලබා ගැනීම
        const userReplyText = getMessageText(replyMsg);
        const idx = parseInt(userReplyText) - 1;

        if (isNaN(idx) || idx < 0 || idx >= topNews.length) return;

        const news = topNews[idx];

        // සම්පූර්ණ පුවත් විස්තරය සැකසීම
        const detailedReport = `
📰 *${news.title}*

📌 *විස්තරය:* ${news.description || news.content || "සම්පූර්ණ විස්තරය ලබාගත නොහැක."}

✍️ *මූලාශ්‍රය:* ${news.source?.name || "NewsAPI"}
📅 *ප්‍රකාශිත දිනය:* ${new Date(news.publishedAt).toLocaleDateString()}

🔗 *සම්පූර්ණ පුවත කියවන්න ලින්ක් එක:*
${news.url}

_Generated by ${botName} News Service_
`;

        // පුවතට අදාළ පින්තූරයක් ඇත්නම් එය සමඟ, නැතහොත් Text එකක් ලෙස යැවීම
        if (news.urlToImage) {
            await client.sendMessage(m.jid, {
                image: { url: news.urlToImage },
                caption: detailedReport
            }, { quoted: replyMsg });
        } else {
            await client.sendMessage(m.jid, { 
                text: detailedReport 
            }, { quoted: replyMsg });
        }

    } catch (err) {
        await m.reply("❌ පුවත් සේවාව ලබාගැනීමේදී දෝෂයක් ඇතිවිය: " + err.message);
    }
});

