// commands/news.js
const { Sparky, isPublic } = require("../lib");
const axios = require("axios");
const config = require("../config");

Sparky({
    name: "news",
    alias: ["පුවත්", "breaking", "n"],
    category: "news",
    fromMe: isPublic,
    desc: "ලංකාවේ සහ ලෝකයේ අලුත්ම පුවත් ලබා ගැනීම"
}, async ({ client, m, args }) => {
    try {
        const botName = config.BOT_INFO?.split(";")[0] || "SADEW-MINI";

        // Loader එකක් යැවීම
        await client.sendMessage(m.jid, { text: "📥 NewsAPI සේවාදායකයෙන් අලුත්ම පුවත් ලබාගනිමින් පවතී..." }, { quoted: m });

        // ඔයාගේ API Key එක යොදාගෙන ලංකාවට අදාළ පුවත් ලබාගැනීම
        const apiKey = "15d4000cd98b4ec59387a8bbb1bb5372";
        const response = await axios.get(`https://newsapi.org/v2/top-headlines?q=Sri+Lanka&apiKey=${apiKey}`, {
            timeout: 10000
        });

        const articles = response.data?.articles;

        if (!articles || articles.length === 0) {
            return await m.reply("❌ මේ වෙලාවේ කිසිදු අලුත් පුවතක් සොයාගත නොහැකි විය.");
        }

        // මුල්ම පුවත් 5ක් වෙන් කරගැනීම
        const topNews = articles.slice(0, 5);
        
        let menuStatus = `
╭───────────────◉
│ *📰 ${botName} NEWS HUB*
├───────────────◉
│✨ NewsAPI Official Service
├───────────────◉\n`;

        topNews.forEach((item, index) => {
            menuStatus += `│ *${index + 1}️⃣ ${item.title.substring(0, 55)}...*\n`;
        });

        menuStatus += `
╰────────────────◉
> ${botName} WhatsApp Bot

*Reply with (1 - 5):*
ඔබට සම්පූර්ණ විස්තරය කියවීමට අවශ්‍ය පුවතේ අංකය Reply කරන්න. 🧧
`;

        // පළමු පුවතේ රූපය (තිබේ නම්) හෝ default රූපය යැවීම
        const imageToShow = topNews[0].urlToImage || "https://res.cloudinary.com/dqlh378fb/image/upload/v1780800370/zanta_media_uploads/y2qrw8srsw1v4dsu5wxv.jpg";

        await client.sendMessage(m.jid, {
            image: { url: imageToShow },
            caption: menuStatus,
            contextInfo: {
                mentionedJid: [m.sender],
                forwardingScore: 1000,
                isForwarded: true
            }
        }, { quoted: m });

        // User Reply Filter
        const filter = (msg) => {
            if (!msg?.message) return false;
            if (msg.key.remoteJid !== m.jid) return false;
            if (msg.key.fromMe) return false;

            const text = msg.message.conversation || msg.message.extendedTextMessage?.text || "";
            return ["1", "2", "3", "4", "5"].includes(text.trim());
        };

        // තත්පර 45ක් පරිශීලකයාගේ පිළිතුර සඳහා රැක සිටීම
        const replyMsg = await new Promise((resolve) => {
            const handler = (chatUpdate) => {
                const msg = chatUpdate.messages?.[0];
                if (filter(msg)) {
                    client.ev.off("messages.upsert", handler);
                    resolve(msg);
                }
            };

            client.ev.on("messages.upsert", handler);

            setTimeout(() => {
                client.ev.off("messages.upsert", handler);
                resolve(null);
            }, 45000); 
        });

        if (!replyMsg) return;

        const selectedIndex = parseInt((
            replyMsg.message.conversation ||
            replyMsg.message.extendedTextMessage?.text ||
            ""
        ).trim()) - 1;

        const selectedNews = topNews[selectedIndex];

        // සම්පූර්ණ විස්තරය සකස් කිරීම
        const detailedReport = `
📰 *${selectedNews.title}*

📌 *විස්තරය:* 
${selectedNews.description || selectedNews.content || "සම්පූර්ණ විස්තරය ලබාගත නොහැක."}

✍️ *මූලාශ්‍රය:* ${selectedNews.source?.name || "NewsAPI"}
📅 *ප්‍රකාශිත දිනය:* ${new Date(selectedNews.publishedAt).toLocaleDateString()}

🔗 *සම්පූර්ණ පුවත කියවන්න ලින්ක් එක:*
${selectedNews.url}

_Generated by ${botName} News Service_
`;

        // පුවතේ පින්තූරයක් තිබේ නම් එය සමඟ විස්තරය යැවීම, නැතහොත් text එකක් ලෙස යැවීම
        if (selectedNews.urlToImage) {
            await client.sendMessage(m.jid, {
                image: { url: selectedNews.urlToImage },
                caption: detailedReport
            }, { quoted: replyMsg });
        } else {
            await client.sendMessage(m.jid, {
                text: detailedReport,
                contextInfo: { isForwarded: true }
            }, { quoted: replyMsg });
        }

    } catch (err) {
        console.error("❌ NewsAPI cmd error:", err);
        await m.reply("❌ පුවත් සේවාවේ තාක්ෂණික දෝෂයකි: " + err.message);
    }
});
